=== maxmeffert/BScThesis/code/megal-xtext/org.softlang.megal.plugins/input/org/softlang/megal/acme/acme.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="company" type="company"/>

  <xs:element name="employee" type="employee"/>

  <xs:complexType name="company">
    <xs:sequence>
      <xs:element name="departments" type="department" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="department">
    <xs:sequence>
      <xs:element name="employees" type="employee" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="employee">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="salary" type="xs:int" use="required"/>
  </xs:complexType>
</xs:schema>

=== maxmeffert/BScThesis/code/megal-xtext/org.softlang.megal.plugins/input/org/softlang/megal/acme/acme.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ACME" xsi:noNamespaceSchemaLocation="./input/org/softlang/megal/acme/acme.xsd">
    <departments name="D0">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D1">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D2">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D3">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D4">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D5">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D6">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D7">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D8">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
    <departments name="D9">
        <employees name="E0" salary="1000"/>
        <employees name="E1" salary="2000"/>
        <employees name="E2" salary="3000"/>
        <employees name="E3" salary="4000"/>
        <employees name="E4" salary="5000"/>
        <employees name="E5" salary="6000"/>
        <employees name="E6" salary="7000"/>
        <employees name="E7" salary="8000"/>
        <employees name="E8" salary="9000"/>
        <employees name="E9" salary="10000"/>
    </departments>
</company>
